### ISSUE TITLE
Exception "Recevied null value from the docker query for container and image count in UnixSocketDataCollector"

### ISSUE THREAD

**Issue by centic9** [Dynatrace/Dynatrace-AppMon-Docker-Monitor-Plugin#2]
When I try to run the plugin on a machine where a Dynatrace Collector is running with configuration SSH-Local, I get the following error, although the socket is available. 

```
~$ ls -al /var/run/docker.sock
srw-rw---- 1 root docker 0 Jul  7 21:50 /var/run/docker.sock
```

Making the socket-file read/writeable for all did not make it work. When I try to connect via ssh I get "2015-07-22 06:39:34 SEVERE [DockerMonitor@Docker Monitor_0] There was a problem while connecting to localhost:22"

Error details are:

```
2015-07-22 06:30:14 SEVERE [DockerMonitor@Docker Monitor_0] getDataLocally.connect-NoCause:org.newsclub.net.unix.AFUNIXSocketException: No such file or directory (socket: /run/docker.sock)
    at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
    at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:125)
    at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:97)
    at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:87)
    at com.dynatrace.docker.collector.UnixSocketDataCollector.getDataLocally(UnixSocketDataCollector.java:330)
    at com.dynatrace.docker.collector.UnixSocketDataCollector.collectContainerAndImageCount(UnixSocketDataCollector.java:76)
    at com.dynatrace.docker.DockerMonitor.execute(DockerMonitor.java:157)
    at com.dynatrace.diagnostics.sdk.UserPluginManager.executePlugin(SourceFile:565)
    at com.dynatrace.diagnostics.sdk.MonitorPluginExecutor.execute(SourceFile:51)
    at com.dynatrace.diagnostics.sdk.MonitorPluginExecutor.execute(SourceFile:26)
    at com.dynatrace.diagnostics.scheduling.impl.ServerJobCenterRegistry.a(SourceFile:189)
    at com.dynatrace.diagnostics.scheduling.impl.ServerJobCenterRegistry.a(SourceFile:412)
    at com.dynatrace.diagnostics.scheduling.impl.ServerJobCenterRegistry.execute(SourceFile:336)
    at com.dynatrace.diagnostics.scheduling.impl.SchedulerJob.a(SourceFile:101)
    at com.dynatrace.diagnostics.scheduling.impl.SchedulerJob.work(SourceFile:92)
    at com.dynatrace.diagnostics.scheduling.impl.SchedulerJob.executeJobInfo(SourceFile:241)
    at com.dynatrace.diagnostics.scheduling.impl.QuartzJob.execute(SourceFile:45)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
    at com.dynatrace.diagnostics.scheduling.impl.QuartzThreadPool$WorkerThread.run(SourceFile:788)
2015-07-22 06:30:14 SEVERE [DockerMonitor@Docker Monitor_0] Recevied null value from the docker query for container and image count in UnixSocketDataCollector. Please check log files to find the reason.
```

**Comment by centic9** [comment]
I think this is because we are running the Dynatrace Collector itself as a Docker Container and the access is not possible from inside the Container to the Host machine...
